= Wenen, Österreichische Nationalbibliothek Cod. 11883: doctoraalscriptie Muziekwetenschap Universiteit van Amsterdam
Eric J. Malotaux
november 1984
:doctype: book
:title-page:
:toc:
:toc-title: Inhoud
:sectnums:
:chapter-signifier: Hoofdstuk
:authors:
:content:
:name-only: Eric Jan Malotaux
:name-only: Scriptiebegeleider: Prof. Dr. C.J. Maas

[preface]
= Voorwoord

Deze scriptie vindt zijn oorsprong in een doctoraalwerkcollege over het manuscript _Wenen, Österreichische Nationalbibliothek, Cod. 11883_, hierna te noemen _Wenen 11883_, dat in het voorjaar van 1984 door Professor C.J. Maas werd gegeven aan het Instituut voor Muziekwetenschap van de Universiteit van Amsterdam.
Aan dit werkcollege name deel behalve ikzelf Peter van den Burg, Peter Banning, Kees Schilder, Frans Wiering, Jeffry van der Elst, Liesbeth Nederstigt en Leon Kessels, die ik graag wil bedanken voor hun toestemming om de resultaten van het werkcollege in deze scriptie te verwerken.
De schriftelijke neerslag van het werkcollege in de vorm van transcripties en referaten is overigens te vinden in twee multobanden in de bibliotheek van het Instituut voor Muziekwetenschap, tot nu toe nog zonder signatuur.
Verder wil ik graag nog bedanken B. Kahmann voor het ter beschilling stellen van zijn foto's van _Cambridge, Magdalen College, Pepys Library, ms. 1760_, Willem Hering voor zijn hulp in de bibliotheek van het Instituut voor Muziekwetenshap, Malotaux - Electronic Systems Design - voor het gebruik van hun computer voor het typwerk, en niet in het minst Professor Maas voor zijn ondersteuning en begeleiding.

Eric Jan Malotaux +
Amsterdam, november 1984

== Inleiding

_Wenen 11883_ is een papieren manuscript, formaat 21 bij 28,7 cm, bestaande uit 325 bladen, dat 28 missen, een _Regina coeli_ en een los driedelig _Agnus Dei_ bevat van deels bekende componisten zoals Josquin des Prez, Jacob Obrecht, Johannes Ockeghem en Heinrich Isaac, deels minder bekende componisten zoals Mattheus Pipelare, Johannes Ghiselin-Verbonnet, Johannes Prioris, Jacobus Barbireau en Lupus, en deels vrijwel onbekende of volslagen onbekende componisten zoals Johannes Notens, Hieronimus Winters, Amanus Faber, Henricus Sevendonck, Nicolaus Carlir en Joh.
Sticheler.
Bovendien staan er nog een stuk af tien anonieme werken in het manuscripts.
Het is geen mooi manuscript, zoals vele van de bekende prachtige koorboeken uit het begin van de 16e eeuw, die door koningen en andere hooggeplaatste personen als relatiegeschenken werken gebruikt.
Het schrift is vaak slordig en klein, soms vrijwel onleesbaar, en zeker ongeschikt voor een koor om uit te zingen.
Verschillende schrifttypen zijn te onderscheiden, wat erop wijst dat delen van het manuscript van verschillende copiisten afkomstig zijn.

_Wenen 11883_ is vaak gebruikt bij het verzorgen van uitgaven van de verzamelde werken van erin vertegenwoordigde componisten, eerst van de bekende, later ook van de minder bekende.
Aandacht voor het manuscript beperkte zich daarbij vrijwel steeds tot die gedeelten van het manuscript waar het werk van de betreffende componist zich bevond.
De werken van de weinig of niet bekende componisten, en de anonieme werken hebben zich ook weinig in musicologische belangstelling mogen verheugen.
Met het manuscript als geheel heeft alleen Nowak <<NOWAK>> zich beziggehouden, die het bespreekt in zijn studie over de Fugger-manuscripten in de Österreichische Nationalbibliotheek (1948).
Nowak concludeert daarin onder meer dat het manuscript zeer belangwekkend is, en dat een afzonderlijke, uitvoerige studie ervan dringend gewenst is.
Al met al voldoende aanleiding voor Professor Maas om er een werkcollege aan te wijden, en voor mij om er een doctoraalscriptie over te schrijven.

Het onderzoek tijdens het werkcollege heeft zich eerst voornamelijk gericht op bibliografische aspecten van _Wenen 11883_, zoals het samenstellen van een betrouwbare inhoudsopgave, het thuisbrengen van de anonieme composities, het binnen nauwere grenzen vaststellen van de tijd van ontstaan, het identificeren van de copiisten en het zoeken van concordanties met andere bronnen, en later, nadat gebleken was dat dit slechts weinig nieuws opleverde, vooral op inhoudelijke aspecten, zoals transcriptie en bestudering van de niet-uitgegeven werken, en het zoeken van modellen daarvan.
Ook is getracht nadere biografische informatie te vinden over de vrijwel of volslagen onbekende componisten, meestal met weinig resultaat.

Het doel van deze scriptie is ten eerste het ordenen en waar mogelijk aanvullen van de bibliografische gegevens over _Wenen 11883_. Hiertoe heb ik een literatuurstudie gemaakt, waarbij ik geprobeerd heb alle literatuur waarin het manuscript besproken of genoemd wordt te vinden.
Ik heb de lijst van catalogi van bibliotheken en van afzonderlijke (groepen van) manuscripten, die Frans Wiering voor het werkcollege had gemaakt (aanwezig in één van de in het voorwoord genoemde multobanden), de catalogi van het microfilmarchief van het Instituut voor Muziekwetenschap, en de catalogus van werken van Nederlandse componisten in Italiaanse bibliothekenfootnote:[zie <<SMIJERS1935>>] in het Instituut voor Muziekwetenschap van de Rijksuniversiteit Utrecht doorgenomen op zoek naar concordanties.
Overigens met uiterst mager resultaat: één nieuwe concordantie, namelijk die van de _Missa Adiutorium nostrum_ in MusBS F. Wat ik niet heb gedaan is het doornemen van manuscripten of microfilms daarvan om te zien of er zich onder anonieme of foutief toegeschreven werken soms nog concordanties bevinden.
Een dergelijk tijdrovend werk kan misschien nog informatie opleveren die mij tot dusver is ontgaan.
Alle bibliografische gegevens zijn samengevat in de inventaris.
Het vermelden van de modellen van de _Missa Misericoria domini_ van Heinrich Isaac, en van de vier missen van Mattheus Pipelare was helaas door tijdgebrek niet meer mogelijk, maar deze modellen zijn - voor zover ze bekend zijn - ongetwijfeld te vinden in de wèl vermelde studies over het werk van deze componisten.
Om het vergelijken van de inhoud met die van andere bronnen te vergemakkelijken heb ik een incipitindex gemaakt.

Het tweede doel van mijn scriptie was eerst het nader bestuderen van de twee missen, de _Missa per Alamyr_ van Hieronimus Winters, en de anonieme _Missa Pourquoy alles vous seulette_, die mijn tijdens het werkcollege ter transcriptie en bestudering waren toegewezen.
Later heb ik besloten om in plaats van de mis van Winters de anonieme _Missa Adiutorium nostrum_ te bestuderen, omdat de literatuurstudie allerlei interessante informatie over het model van deze mis opleverde, en ook omdat de enige door mij gevonden concordantie op deze mis betrekking heeft.
De analyse van de twee missen richt zich alleen op de parodie-techniek, omdat een dergelijke analyse het meeste licht leek te kunnen werpen op de herkomst, zowel wat tijd als plaats betreft, van de werken, en daardoor misschien ook op de herkomst van het manuscript.
Bovendien is studie van parodie-missen uit deze periode op zichzelf al interessant genoeg, en tot dusver nog weinig beoefend.footnote:[Zie <<LOCKWOOD1964>> en <<LOCKWOOD1966>>.]

Er zijn nog enkele onderwerpen overgebleven die ik had willen bestuderen, maar waar ik niet aan toegekomen ben.
Zo had ik de versies van de missen van Josquin, Barbireau, Isaac, Notens, Obrecht en Prioris willen vergelijken met de versies van hun concordanties, met het doel om stemma's vast te stellen, om zo meer zicht te krijgen op de plaats van _Wenen 11883_ in de overlevering van deze werken.
Dit zou dan een nauwkeuriger datering van ons manuscript mogelijk hebben moeten maken, en in het algemeen meer informatie hebben kunnen opleveren omtrent ontstaan, gebruik en functie ervan.
Ik had ook willen proberen om een studie te maken van de opbouw van het manuscript in lagen, op grond van criteria als bijvoorbeeld type mis en schriftbeeld.
Daarvoor zou dan eigenlijk een reis naar Wenen nodig geweest zijn om het manuscript te onderzoeken op details die op een microfilm niet zichtbaar zijn.
Tenslotte lag het in mijn bedoeling om een hoofdsuk te wijden aan het ontwerpen van theorieën omtrent ontstaan, gebruik en functie van _Wenen 11883_, en van daaruit in het algemeen over de productie en distributie van genoteerde muziek in de vroege 16e eeuw.
In het geval dat iemand zich ooit nog eens bezighoudt met deze onderwerpen hoop ik dat deze scriptie de weg naar een dergelijk onderzoek enigszins geplaveid heeft.

== Samenvatting literatuur

_Wenen 11883_ is niet bepaald een onbekend manuscript.
De inhoud ervan is al bekend sinds 1875, toen deel VII van de _Tabulae_ footnote:[Joseph Mantuani (1875)] werd gepubliceerd, waarin _Wenen 11883_ gecatalogiseerd is.
Doordat het manuscript onder meer werken bevat van enkele van de breoemdste componisten van de tweede helft van de 15e eeuw en het begin van de 16e eeuw, is het ook geregeld gebruikt in studies over het werk van deze componisten.

De eerste die _Wenen 11883_ na het verschijnen van de _Tabulae_ noemt, is Robert Eitner <<EITNER>> in de _Quellenlexicon_, in de artikelen over componisten die met hun werk in het manuscript zijn vertegenwoordigd.
Eitner vermeldt dan alleen dat het een manuscript uit de 164 eeuw is, dat het 325 bladen telt, en het nummer van de betreffende compositie.

De volgende die het manuscript noemt, is Johannes Wolf <<WOLF>> in de uitgave van werken van Jacob Obrecht.
Wolf geeft tweemaal een beschrijving van het manuscript: éénmaal in de inleiding van de _Missa L'homme armé_ footnote:[_Werken_, deel V, voor pagina 53], en éénmaal in de inleiding van de _Missa sine nomine_ footnote:[_Werken_, deel V, voor pagina 157].
De twee beschrijvingen stemmen echter niet geheel met elkaar overeen.
In de inleiding van de _Missa L'homme armé_ noemt hij naast een _Regina coeli laetare_ en een _Agnus_ een aantal van 28 missen, terwijl hij het in de inleiding van de _Missa sine nomine_ heeft over 29 missen een _Regina coeli_.
Onder de componisten noemt Wolf in de eerste beschrijving wèl Johannes Notens, maar de de tweede beschrijving niet.
Tenslotte begint volgens de eerste beschrijving de _Missa L'homme armé_ op folio 51 recto, en volgens de tweede beschrijving op folio 52 recto.
Beide keren vermeldt Wolf als ontstaanstijd van het manuscript het einde van de 15e eeuw.

George van Doorslaer <<DOORSLAER1933>> noemt _Wenen 11883_ alleen maar in verband met Nicolaus Carlir, die in het manuscript "sangmeyster zu Anthorff" wordt genoemd, en over wie van Doorslaer enige interessante informatie heeft verzameld.
Vrijwel de enige informatie trouwens, die over deze componist, van wie alleen de mis in _Wenen 11883_ bekend is, te vinden is.

Smijers <<SMIJERS1939>>footnote:[In de inleiding van de _Missa Malheur me bat_, _Werken_ afl.19, p. VII.] geeft behalve een beschrijving ook een inhoudsopgave, die kennelijk ontleend is aan de _Tabulae_.
Smijers identificeert verde de _Missa 4 vocum_ op folia 42'-51 als de _Missa quant jái au cor_ van Heinrich Isaac, de _Missa 3 voc_ van Obrecht als _Missa De tous biens_,footnote:[Dit had Otto Gombosi al ontdekt: zie Gombosi (1925), 45-47.] en de _Missa 4 voc_ van Johannes Notens eveneens als een _Missa De tous biens_.
Als ontstaanstijd noemt hij het begin van de 16e eeuw.

Enige informatie over minder bekende werken in _Wenen 11883_ vinden we in het boek van du Saar <<SAAR>> over Jacobus Barbireau.
Behalve over de _Missa Faulx perversa_ van Barbireaufootnote:[pp. 38-48] schrijft du Saar ook over de _Missa Pourquoy alles vous seullette_, die anoniem staat op folia 195'-198footnote:[pp. 32].
Du Saar weerlegt de toeschrijving aan Jacobus Barbireau, gedaan door J.B. Weckerlin <<WECKERLIN>>footnote:[pp. 115. Volgens du Saar heeft M. Bottée de Toulmont tussen 1831 en 1850, toen deze laatste bibliothecaris was van de Bibliothèque du Conservatoire de Paris, afschriften laten maken voor zijn bibliotheek van verscheidene Weense manuscripten, waaronder Wenen1783, 11883 en 15497. Het afschrift van _Wenen 11883_ bevindt zich nu in de Bibliothèque Nationale onder de signatuur Cons.Rés. F.1332.], op grond van stylistische criteria.
Hij meent tevens, dat de _Tabulae_ en Smijers ten onrechte aangeven dat deze mis slechts de folia 196'-198 beslaan, en dat daarentegen deze mis doorloopt tot folia 204. Volgens du Saar past één mis nooit op zo weinig foliafootnote:[Du Saar had ongelijk: weliswaar is de opgave van Smijers niet correct, aangezien de _Missa Pourquoy alles vous seullette_ al op folio 195' begint in plaats van op folio 196', maar de mis eindigt inderdaad op folio 198. De copiist heeft gewoon verschrikkelijk klein geschreven. Du Saar merkte trouwens ook de verschillen op in de twee beschrijvingen van Johannes Wolf. De ene keer spelt Wolf Barbariaw, en de andere keer Barberiaw.].
Op pagina 60 tenslotte noemt hij Matheus Pipelare als componist van de twee laatste missen van het manuscript, op folia 305-315 en 315'-325, die Smijers anoniem genoemd had.
Du Saar is trouwens de enige, die het bovengenoemde artikel van G. van Doorslaer over "Nicole Carlier" noemt.

Het volgende anonieme werk dat thuisgebracht kon worden, is de _Missa 4 voc._ op folia 208-221, die de _Missa Prolationum_ van Johannes Ockeghem blijkt te zijn.
De versie van deze mis in _Wenen 11883_ is een "resolutio" van de oorspronkelijke notatie in twee stemmen, zoals in de "Chigi-codex"footnote:[ROMA, Biblioteca Apostolicana Vaticana, Chigiana, C.VIII.234, fol. 106'-114.].
Dit staat in de uitgave van <<PLAMENAC>> van de werken van Johannes Ockeghem.
Plamenac zegt dat Professor Newman W. Powell dit ontdekt en het hem meegedeeld heeft.
Verder geeft Plamenac een beknopte beschrijving van _Wenen 11883_, die vrijwel overeen komt met die van Smijers, en een gedetailleerde collatie van de "Weense" versie van de _Missa Prolationum_ met die van de Chigi-codex."

[bibliography]
== Bibliografie

* [[[ANTWERPS]]] _Het Antwerps Liedboek: 87 melodieën op teksten uit "Een Schoon Liedekens-Boeck"van 1544_ / uitgegeven door K. Vellekoop en H. Wagenaar-Nolthenius; met medewerking van W.P. Gerritsen en A.C. Hemmes-Hoogstadt.&nbsp;- 2e druk.&nbsp;- Amsterdam : Vereniging voor Nederlandse Muziekgeschiedenis, 1975.&nbsp;- 2 delen.
* [[[DOORSLAER1928, Doorslaer (1928)]]] G, van Doorslaer: "_Calligraphes de musique à Malines au XVIe siècle_", in: _Bulletin du Cercle archéologique, litteraire, et artistique de Malines_, 33 (1928), 91-102.
* [[[DOORSLAER1933, Doorslaer (1933)]]] G. van Doorslaer: "_Nicole Carlier(gest. 1523), Componist en Zangmeester te Antwerpen_" in: _Antwerps Archievenblad_, 2e reeks, 8 (1933), 10-12.
* [[[DOORSLAER1934, Doorslaer (1934)]]] G. van Doorslaer: "_La chapelle musicale de Philippe le Beau_", in: _Revue belge d'archéologie et d'histoire de l'art_, 4 (1934), 21-57, 139-165.
* [[[EITNER, Eitner>]]] Robert Eitner: _Biographisch-Bibliographisches Quellen-Lexicon der Musiker und Musikgelehrten christlichter Zeitrechnung bis Mitte des neunzehnten Jahrhunderts_.&nbsp;- 2e verbesserte Auflage in 11 Bänden.&nbsp;- Graz : Akademische Druck- und Verlags-Anstalt, 1959.
* [[[LOCKWOOD1964, Lockwood (1964)]]] Lewis Lockwood: "_A view of the Early Sixteenth-Century Parody Mass_" in: _The Department of Music, Queens College of the City University of New York: Thenty-fifth Anniversary Festschrift (1937-1962)_, 53-77 edited by Albert Mell.&nbsp;- New York.&nbsp:&nbsp;City University of New York, 1964.
* [[[LOCKWOOD1966, Lockwood 1966)]]] Lewis Lockwood: "_On 'Parody' as Term and Concept in 16th-Century Music_" in: _Aspects of Medieval & Renaissance Music: A Birthday Offering to Gustave Reese_, 560-575&nbsp;/&nbsp; ed. by Jan LaRue.&nbsp;- New York&nbsp;: Nortin, 1966.
* [[[NOWAK, Nowak (1948)]]] Leopold Nowak: "_Die Musikhandschriften aus Fuggerschem Besitz in der Österreichischen Nationalbibliotheek_" in: _Die Österreichische Nationalbibliotheek: Festschrift herausgegeven zum 25 Jährigen Dienstjubiläum... Dr. Josef Bick_, 505-515.&nbsp;- Wien, 1948.
* [[[PLAMENAC, Plamenac (1966)]]] Dragan Plamenac (ed.): _Johannes Ockeghem: Collected Works_.&nbsp;- 2nd corrected edition.&nbsp;- [s.l.]&nbsp:&nbsp;American Musicological Society, 1966.&nbsp-&nbsp;(Studies and Documents; 1).
* [[[SAAR, Saar 1949)]]] Johannes du Saar: _Het leven en de composities van Jacobus Barbireau_.&nbsp;- Utrecht : de Haan, 1946.&nbsp;- Proefschrift Rijksuniversiteit Utrecht.
* [[[SMIJERS1935, Smijers (1935)]]] A. Smijers: "_Vijftiende en zestiende eeuwsche muziekhandschriften in Italië met werken van Nederlandsche componisten_" in: TVNM 14 1935), 165-181.
* [[[SMIJERS1939,Smijers (1939)]]] A. Smijers (ed.): Afl. 19: _Missa Malheur me bat_.&nbsp;- Leipzig : Kistner & Siegel, 1939.
* [[[WECKERLIN, Weckerlin]]] J.B. Weckerlin: _La chanson populaire_.&nbsp;- Paris, 1886.
* [[[WOLF, Wolf]]] Johannes Wolf (ed.): _Werken van Jacob Obrecht_.&nbsp;- Amsterdam&nbsp;&nbsp;; Leipzig&nbsp;: Vereeniging voor Noord-Nederlandse Muziekgeschiedenis, 1908-1921.