name: Generate Lilypond music sheets
on:
  push:
    branches:
      - main
jobs:
  build_sheets:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    env:
        LILYPOND_FILES: "*.ly"
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Checkout Source 
        uses: actions/checkout@v1
      - name: Get changed files
        id: getfile
        run: |
          echo "::set-output name=files::$(find ${{github.workspace}} -name "${{ env.LILYPOND_FILES }}" -printf "%P\n" | xargs)"
      - name: LILYPOND files considered echo output
        run: |
          echo ${{ steps.getfile.outputs.files }}
      - name: Generate PDF music sheets
        uses: alexandre-touret/lilypond-github-action@master
        with:
            args: -V -fpdf -fmidi ${{ steps.getfile.outputs.files }}
      - name: Push Local Changes
        run: |
          mkdir -p ${{github.workspace}}/docs/
          mv -f *.midi ${{github.workspace}}/docs/
          mv -f *.pdf ${{github.workspace}}/docs/
          mv -f *.png ${{github.workspace}}/docs/
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: ${{github.workspace}}/docs/
      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v1
